name: Builder 0
on:
  push:
    branches:
      - 'develop*'
  workflow_dispatch:

jobs:
  builder:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-tags: true

      - name: Show environment
        run: env
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: echo "$RUNNER_CONTEXT"
        
      - name: Generate build number
        id: build-number
        uses: ./.github/workflows/build-number.yml@develop-v1.1.0-0
            