name: Builder 1
run-name: "${{ github.workflow }} triggered by ${{ github.triggering_actor }}"

on:
  push:
    branches:
      - 'develop*'
  workflow_dispatch:

jobs:
  builder:
    name: Build application's Variant-1 
    needs:
      - get-package-version
      - get-build-number
    runs-on: ubuntu-latest
    env:
      PACKAGE_VERSION: ${{ needs.get-package-version.outputs.packageVersion }}
      BUILD_NUMBER: ${{ needs.get-build-number.outputs.build_number }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-tags: true
        
      - name: Show environment
        run: env

      - name: Dump env context
        env:
          ENV_CONTEXT: ${{ toJson(env) }}
        run: echo "$ENV_CONTEXT"
        
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
        
      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: echo "$RUNNER_CONTEXT"
        
      - name: Dump needs outputs
        env:
          OUTPUT_CONTEXT: ${{ toJson(needs) }}
        run: echo "$OUTPUT_CONTEXT"
        
      - name: Dump inputs context
        env:
          INPUTS_CONTEXT: ${{ toJson(inputs) }}
        run: echo "$INPUTS_CONTEXT"
      
      - name: Show build number
        run: |
          echo packageVersion: ${{ needs.get-package-version.outputs.packageVersion }}
          echo PACKAGE_VERSION: $PACKAGE_VERSION
          echo build_number: ${{ needs.get-build-number.outputs.build_number }}
          echo BUILD_NUMBER: $BUILD_NUMBER
        
  get-build-number:
    name: Retrieve build number
    needs: 
      - get-package-version
    uses: ./.github/workflows/build-number.yml
    with:
      prefix: "${{ needs.get-package-version.outputs.packageVersion }}/"

  get-package-version:
    name: Retrieve package version 
    uses: ./.github/workflows/project-version.yml
    with:
      project_file: "./workflow-sandbox/workflow-sandbox.csproj"
      tag_name: "PackageVersion"