name: .NET publish release candidate package
on:
  pull_request:
    types:
      - opened
      - reopened
#      - synchronize
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Setup .NET Core @ Latest
        uses: actions/setup-dotnet@v3
        with:
          source-url: https://nuget.pkg.github.com/mdougherty-magaya/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
        
      - name: Cache .NET files
        id: cache-dotnet
        uses: actions/cache@v3
        env:
          cache-name: cache-dotnet
        with:
          path: ~/.dotnet
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/workflow-sandbox.csproj') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - if: ${{ steps.cache-npm.outputs.cache-hit != 'true' }}
        name: List the state of node modules
        continue-on-error: true
        run: dotnet workload list
        
      - name: Install workloads (Not Linux)
        if: runner.os != 'Linux'
        run: dotnet workload install maui-android maui-ios

      - name: Install workloads (Not Linux)
        if: runner.os == 'Linux'
        run: dotnet workload install maui-android
      
      - name: Restore Packages
        run: dotnet restore
        
      - name: Show condition values
        run: |
          echo "github.event_name=${{ github.event_name }}"
          echo "pull_request.number=${{ github.pull_request.number }}"
          echo "ref=${{ github.ref_name }}"
          echo "default_branch=${{ github.event.repository.default_branch }}"

      - name: Set package version suffix
        if: github.event_name == 'pull_request'
        env:
          EVENT_NUMBER: ${{ github.event.number }}        
        run: |
          echo "VERSION_POSTFIX=-rc.${EVENT_NUMBER}.${GITHUB_RUN_NUMBER}" >> "$GITHUB_ENV"

      - name: Build
        run: dotnet build workflow-sandbox/workflow-sandbox.csproj --configuration Release --no-restore

      - name: Deploy generated package to GitHub registry
        run: dotnet nuget push ./workflow-sandbox/bin/Release/workflow-sandbox*.nupkg --api-key ${{secrets.PUBLISH_TOKEN}} --skip-duplicate --no-symbols
        
      - name: Show environment
        env:
          EVENT_NUMBER: ${{ github.event.number }}
        run: env
