name: .NET publish
on:
  push:
    branches:
      - "*"

jobs:
  build:
    runs-on: macos-latest    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Setup .NET Core @ Latest
        uses: actions/setup-dotnet@v3
        with:
          source-url: https://nuget.pkg.github.com/mdougherty-magaya/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
        
      - name: Install workloads
        run: dotnet workload install maui-android maui-ios
      
      - name: Restore Packages
        run: dotnet restore

      - name: Set package version v1
        run: |
          echo "PACKAGE_VERSION=1.0.${GITHUB_RUN_NUMBER}-preview-${GITHUB_REF_NAME}+$(echo $GITHUB_SHA | cut -c1-8)" >> "$GITHUB_ENV"

#      - name: Show environment
#        env:
#          PACKAGE_VERSION: 2.0.0-alpha.${GITHUB_RUN_NUMBER}+${GITHUB_SHA:0:8}
#        run: env
      
      - name: Build
        run: dotnet build workflow-sandbox/workflow-sandbox.csproj --configuration Release --no-restore

      - name: Deploy generated package to GitHub registry
        run: dotnet nuget push ./workflow-sandbox/bin/Release/workflow-sandbox*.nupkg --api-key ${{secrets.PUBLISH_TOKEN}} --skip-duplicate --no-symbols
        
      - name: Show environment
        run: env
