name: .NET publish
on:
  push:
    branches:
      - "*"
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Setup .NET Core @ Latest
        uses: actions/setup-dotnet@v3
        with:
          source-url: https://nuget.pkg.github.com/mdougherty-magaya/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
        
      - name: Cache .NET files
        id: cache-dotnet
        uses: actions/cache@v3
        env:
          cache-name: cache-dotnet
        with:
          path: ~/.dotnet
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/workflow-sandbox.csproj') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - if: ${{ steps.cache-npm.outputs.cache-hit != 'true' }}
        name: List the state of node modules
        continue-on-error: true
        run: dotnet workload list
        
      - name: Install workloads
        run: dotnet workload install maui-android maui-ios
      
      - name: Restore Packages
        run: dotnet restore
        
      - name: Show condition values
        run: |
          echo "ref=${{ github.ref }}"
          echo "default_branch=${{ github.event.repository.default_branch }}"
          echo "default-branch.macro=$default-branch"

        if : ${{ github.ref != github.event.repository.default_branch }}
      - name: Not default branch
        run: |
          echo "Not default branch"
          
        if : ${{ github.ref == github.event.repository.default_branch }}
      - name: Default branch
        run: |
          echo "Default branch"
        
      - name: Set package version v1
        run: |
          echo "VERSION_POSTFIX=alpha-${GITHUB_RUN_NUMBER}+$(echo $GITHUB_REF_NAME | tr '[:upper:]' '[:lower:]')-$(echo $GITHUB_SHA | cut -c1-8)" >> "$GITHUB_ENV"

      - name: Build
        run: dotnet build workflow-sandbox/workflow-sandbox.csproj --configuration Release --no-restore

      - name: Deploy generated package to GitHub registry
        run: dotnet nuget push ./workflow-sandbox/bin/Release/workflow-sandbox*.nupkg --api-key ${{secrets.PUBLISH_TOKEN}} --skip-duplicate --no-symbols
        
      - name: Show environment
        run: env
